### PR TITLE
Added lots of tests

### PR DESCRIPTION
**Pull request by cilice**
I’ve created a few tests with Ava, I’ll see how it works.. the code should be somehow rewritten to increase coverage, if you care.

### CODE REVIEW

**Comment by cilice** [comment]
Weird, somehow travis says 4.2 build failed, but it works for me :sob:

**Comment by kahlil** [comment]
In Node v4.2.1 if I do a clean `npm i` in this branch and run `npm test` this happens: 

```sh
npm test

> @reactive/fido@1.2.0 test /Users/klechelt/Code/reactive/fido
> ava


  ✖ cli › cli version spawn EACCES
  ✖ cli › cli help spawn EACCES
  ✖ cli › cli input spawn EACCES
  ✔ test › format
  ✔ test › parseXML/getXMLresult
  ✔ test › parseXML/getResult
  ✔ test › getReviews

  3 tests failed

  1. cli version
  Error: spawn EACCES
    at Test.fn (/Users/klechelt/Code/reactive/fido/test/cli.js:18:37)
    at Promise._execute (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:76:14)
    at tryCatcher (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/util.js:11:23)
    at Object.gotValue (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:488:31)
    at Promise._settlePromise (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:545:18)
    at Promise._settlePromiseCtx (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:582:10)
    at Async._drainQueue (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:130:12)
    at Async._drainQueues (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:16:14)

  2. cli help
  Error: spawn EACCES
    at Test.fn (/Users/klechelt/Code/reactive/fido/test/cli.js:32:37)
    at Promise._execute (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:76:14)
    at tryCatcher (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/util.js:11:23)
    at Object.gotValue (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:488:31)
    at Promise._settlePromise (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:545:18)
    at Promise._settlePromiseCtx (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:582:10)
    at Async._drainQueue (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:130:12)
    at Async._drainQueues (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:16:14)

  3. cli input
  Error: spawn EACCES
    at Test.fn (/Users/klechelt/Code/reactive/fido/test/cli.js:52:37)
    at Promise._execute (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/debuggability.js:142:9)
    at Promise._resolveFromExecutor (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:459:18)
    at new Promise (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:76:14)
    at tryCatcher (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/util.js:11:23)
    at Object.gotValue (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:488:31)
    at Promise._settlePromise (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:545:18)
    at Promise._settlePromiseCtx (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/promise.js:582:10)
    at Async._drainQueue (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:130:12)
    at Async._drainQueues (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/klechelt/Code/reactive/fido/node_modules/bluebird/js/release/async.js:16:14)

npm ERR! Test failed.  See above for more details.
```

**Comment by cilice** [comment]
It actually comes from having no execution rights on /lib/bin/cli.js. like missing `chmod +x lib/bin/cli.js`. Latest commit fixes this.

**Comment by kahlil** [comment]
beautiful :heart: thank you

**Comment by hglattergotz** [comment]
Thank you @cilice !!

**Pull request merged**
